# Manifest file for automated deployments to our user testing environment
# Main manifest.yml can be found in the root level directory.
---
inherit: ../../manifest.yml
host: wds-microsite-user-testing
